apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: cchess

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cchess
  name: gateway-role
rules:
  - resources:
      - statefulsets
    apiGroups: ["apps"]
    verbs:
      - get
      - list
      - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-role-binding
  namespace: cchess
subjects:
  - kind: ServiceAccount
    name: gateway-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway-role
