apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: cchess

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-role
rules:
  - resources:
      - pods
    apiGroups: ["*"]
    verbs:
      - create
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-role-binding
  namespace: cchess
subjects:
  - kind: ServiceAccount
    name: gateway-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway-role
