apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
  namespace: cchess
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  serviceName: "gateway"
  template:
    metadata:
      labels:
        app: gateway
    spec:
      dnsPolicy: Default
      serviceAccountName: gateway-sa
      containers:
        - name: match-gateway
          image: 'docker.pkg.github.com/elvisigkeit/match_gateway/match_gateway:0.2'
          ports:
            - containerPort: 8000
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              host: ''
              path: /
              port: 8000
              scheme: ''
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000